### ISSUE TITLE
Obtener Semilla

### ISSUE THREAD

**Issue by Galathar** [waflessnet/sii-bash#3]
al ejecutar ./consumewsdl.sh (certificado) (clave) (servidor) me sale el error "Error:4 No existe semilla,favor verifique su acceso al WSDL CrSeed.jws", modifiqué la URL por la actual https://ws1.sii.cl/WSAUT/services/CrSeed?WSDL. Cómo lo puedo solucionar?

este el XML resultante:

<?xml version='1.0' ?>
<env:Envelope xmlns:env='http://schemas.xmlsoap.org/soap/envelope/'>
<env:Body>
<env:Fault>
<faultcode>env:Client</faultcode>
<faultstring>Internal Error</faultstring>
</env:Fault>
</env:Body>
</env:Envelope>

**Comment by waflessnet** [comment]
Hola @Galathar  favor verifica que tienes instalado  "recode" en tu  linux

**Comment by ffflabs** [comment]
No sé que URL será esa, pero la que yo uso es
https://palena.sii.cl/DTEWS/CrSeed.jws?WSDL

(Eso es producción)

El SII está lleno de.subdominios abandonados.
