### ISSUE TITLE
Problemas al ejecturar el sh

### ISSUE THREAD

**Issue by joseenriqe97** [waflessnet/sii-bash#4]
Cuando ejecuto el script me sale este error. `func=xmlSecOpenSSLEvpSignatureExecute:file=evp_signatures.c:line=466:obj=rsa-sha1:subj=EVP_SignFinal:error=4:crypto library function failed:openssl error: 101236899: digital envelope routines: EVP_PKEY_sign invalid key
func=xmlSecTransformDefaultPushBin:file=transforms.c:line=1921:obj=rsa-sha1:subj=xmlSecTransformExecute:error=1:xmlsec library function failed:final=1
func=xmlSecTransformIOBufferClose:file=transforms.c:line=2547:obj=rsa-sha1:subj=xmlSecTransformPushBin:error=1:xmlsec library function failed: 
func=xmlSecTransformC14NPushXml:file=c14n.c:line=243:obj=c14n:subj=xmlOutputBufferClose:error=5:libxml2 library function failed:xml error: 0: NULL
func=xmlSecTransformCtxXmlExecute:file=transforms.c:line=1037:obj=c14n:subj=xmlSecTransformPushXml:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=550:obj=unknown:subj=xmlSecTransformCtxXmlExecute:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxSign:file=xmldsig.c:line=286:obj=unknown:subj=xmlSecDSigCtxSignatureProcessNode:error=1:xmlsec library function failed: 
Error: signature failed 
Error: failed to sign file "tmp/semilla.xml"
Error:5 error al crear el token estado:`
Ya le he dado todos los permisos al archivo sh.

**Comment by waflessnet** [comment]
Hola @joseenriqe97   por favor verifica que tengas instalado xmlsec1 ? si lo tienes instalado favor  de indicar la version.
Saludos

**Comment by joseenriqe97** [comment]
Tengo instalado la versión xmlsec1 1.2.25 (openssl).

**Comment by waflessnet** [comment]
Puedes adjuntar la tmp/response-semilla.xml y el flujo de salida desde que realizas el ./consumewsdl.sh 
el listado de los archivos  (ls -la ) donde tienes gitclone, 
el S.O (debian-centos-gentoo?) 
- para así poder ayudarte de mejor manera.

**Comment by joseenriqe97** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <soapenv:Body>
  <ns1:getSeedResponse soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:ns1="http://DefaultNamespace">
   <ns1:getSeedReturn xsi:type="xsd:string"><?xml version="1.0" encoding="UTF-8"?><SII:RESPUESTA xmlns:SII="http://www.sii.cl/XMLSchema"><SII:RESP_BODY><SEMILLA>015240319492</SEMILLA></SII:RESP_BODY><SII:RESP_HDR><ESTADO>00</ESTADO></SII:RESP_HDR></SII:RESPUESTA></ns1:getSeedReturn>
  </ns1:getSeedResponse>
 </soapenv:Body>
</soapenv:Envelope>` Ese es el response-semilla. 

Este es el flujo de salida 

`./consumewsdl.sh rodrigo.p12 <clave>
func=xmlSecOpenSSLEvpSignatureExecute:file=evp_signatures.c:line=466:obj=rsa-sha1:subj=EVP_SignFinal:error=4:crypto library function failed:openssl error: 101236899: digital envelope routines: EVP_PKEY_sign invalid key
func=xmlSecTransformDefaultPushBin:file=transforms.c:line=1921:obj=rsa-sha1:subj=xmlSecTransformExecute:error=1:xmlsec library function failed:final=1
func=xmlSecTransformIOBufferClose:file=transforms.c:line=2547:obj=rsa-sha1:subj=xmlSecTransformPushBin:error=1:xmlsec library function failed: 
func=xmlSecTransformC14NPushXml:file=c14n.c:line=243:obj=c14n:subj=xmlOutputBufferClose:error=5:libxml2 library function failed:xml error: 0: NULL
func=xmlSecTransformCtxXmlExecute:file=transforms.c:line=1037:obj=c14n:subj=xmlSecTransformPushXml:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=550:obj=unknown:subj=xmlSecTransformCtxXmlExecute:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxSign:file=xmldsig.c:line=286:obj=unknown:subj=xmlSecDSigCtxSignatureProcessNode:error=1:xmlsec library function failed: 
Error: signature failed 
Error: failed to sign file "tmp/semilla.xml"
Error:5 error al crear el token estado:
`

Y este es el ls 
`certificado.pem   consumewsdl.sh  rGetSeed.xml   rodrigo.p12  semilla-firmada.xml  tmp
claveprivada.pem  README.md       rGetToken.xml  rodrigo.pfx  template.xml
`
Estoy trabajando con ubuntu.

**Comment by waflessnet** [comment]
la clave no es necesaria jeje,  tienes que utilizar un certificado pfx al lanzar el script : 
./consumewsdl.sh /tmp/certificado.**pfx** 'clave@secretasdf09' 
Prueba agregando comillas a la clave.

**Comment by joseenriqe97** [comment]
Me sigue generando el mismo error :(

**Comment by waflessnet** [comment]
Estube realizando pruebas. y no puedo replicar el error que mencionas, adiciolmente busque el "EVP_PKEY_sign invalid key", claramente arroja que la clave del certificado no es correcta, si tubiera tu pfx quizás pudiera replicar de mejor manera el error. ncwapuntes@gmail.com.

**Comment by ffflabs** [comment]
Ojo, esto puede ser por métodos que cambiaron entre versiones de openssl. 
Un problema parecido ocurre cuando intentas compilar ursa en Ubuntu 16.04+

**Comment by cbustosb** [comment]
Hola, tengo el mismo problema, desde que actualicé la version de ubuntu a 18.04. Finalmente, alguien tiene la solución?

**Comment by cbustosb** [comment]
Hola de nuevo... compilé la version 1.2.30 (con --enable-static --enable-static-linking) y ya está solucionado!

**Comment by jparedesimx** [comment]
Tienes las instrucciones de como compilar esa versión de xmlsec1?

**Comment by waflessnet** [comment]
@jparedesimx  en la pagina oficial estan las instrucciones como compilar https://www.aleksey.com/xmlsec/download.html , seguro @cbustosb  lo utilizo de la siguiente manera : 
```
./configure --enable-static --enable-static-linking 
```

lo probé y funciono.
